# fly.toml app configuration file generated for skybridge on 2023-05-12T22:53:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skybridge"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  SKYBRIDGE_BASEURL = "skybridge.fly.dev"
  SKYBRIDGE_SHOW_INDEX = true
  FLY_SWAP = true

[mounts]
  source="skybridge_data"
  destination="/app/database"

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/v2/instance"

[http_service.concurrency]
  type = "requests"
  hard_limit = 999999
  soft_limit = 9999